Virtual Keyboard
katefadeeva/Virtual-Keyboard pull request #1
Opened 2020-04-07 19:24 UTC by katefadeeva

1. [Ссылка на задание](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/codejam-virtual-keyboard.md)
2. [Скриншот работы](https://prnt.sc/ruxyaj)
3. [Ссылка на работу](https://katefadeeva.github.io/Virtual-Keyboard/)
4. Дата сдачи: 07.04.2020 / Дата дедлайна: 07.04.2020 23:59
5. Баллы (100/110)

`минимальный набор (2 / 2):`
+ реализована генерация DOM-элементов и `body` в index.html пустой изначально (может находится только тег `script`): `+20`
+ нажатие на кнопку на физической клавиатуре подсвечивает кнопку на виртуальной (проверять следует нажатие цифр, букв, знаков препинания, `backspace`, `del` (если она присутствует), `enter`, `shift`, `alt`, `ctrl`, `tab`, `caps lock`, `space`, стрелки вниз-вверх-влево-вправо): `+10`

`стандартный набор (2 / 2):`
+ есть переключение между русским и английским языком (сочетание клавиш для переключения языка должно быть указано на странице с клавиатурой), а также сохранение выбранного языка: `+15`
+ клики мышкой по кнопкам на виртуальной клавиатуре или нажатие на кнопки физической клавиатуры, выводят символы в инпут (textarea): `+15`

`дополнительный набор (1 / 1):`
+ реализована анимация нажатия на кнопку: `+15`

`технические требования (2 / 3):`
+ использование в коде фишек стандарта ES6 и выше (classes, деструктуризация и т.д.): `+15`
- использование eslint: `+10` (не успела разобраться)
+ требования к репозиторию, коммитам и PR выполнены: `+10`

`штрафы (0 / 1):`
- ошибки в консоли, связанные с исполняемым кодом (ошибки типа `favicon.ico: Failed to load resource: the server responded with a status of 404` не учитываются) или предупреждения eslint-config-airbnb-base: `-15`

2020-04-08 17:17 UTC, dfolomkin requested changes

2020-04-08 17:17 UTC, dfolomkin commented on keyboard/script.js
> +            element.addEventListener('keydown', (event) => {
если у стрелочной функции 1 аргумент, скобки можно не ставить

2020-04-08 17:17 UTC, dfolomkin commented on keyboard/script.js
> +            function() { Keyboard._changeLanguage()},
почему не стрелочная?

2020-04-08 18:09 UTC, katefadeeva commented on keyboard/script.js
> +            function() { Keyboard._changeLanguage()},
Можно было и стрелочную использовать )

2020-04-09 15:03 UTC, dfolomkin approved these changes
ready to merge

2020-04-09 15:06 UTC, merged